apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mtrack
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: dakshsawhneyy/mtrack-frontend:latest
        name: mtrack-frontend
        ports:
        - containerPort: 5173
        volumeMounts:
        - name: frontend-env
          mountPath: /app/.env  # where app expects .env file
          subPath: .env  # maps secret key to this file
      volumes:
      - name: frontend-env
        secret:
          secretName: frontend-dotfile-secret
          items:
          - key: .env
            path: .env